import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gust_web, GustWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :gust_web, basic_auth: true

config :gust, dags_folder: "/dags"

# DAG Source Configuration
config :gust,
  dag_sources: [
    {"default-folder", type: Gust.DAG.Source.Folder, folder: "/dags"}
  ]

config :gust, dag_runner_supervisor: Gust.DAG.RunnerSupervisor.DynamicSupervisor
config :gust, dag_task_runner_supervisor: Gust.DAG.TaskRunnerSupervisor.DynamicSupervisor
config :gust, dag_scheduler: Gust.DAG.Scheduler.Worker
config :gust, dag_loader: Gust.DAG.Loader.Worker

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
